// Package embedded provides the offline core dictionary subset that
// ships inside the binary via go:embed. It is always loaded; the local
// (downloaded) database overlays it in dict.NewMulti.
//
// The core files under core/ are GENERATED by cmd/dbasebuild — do not
// edit by hand. See word_dbase/frequency/DATA_LICENSE.md for the
// ranking-data provenance.
package embedded

import (
	"bytes"
	"compress/gzip"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"

	"github.com/yodeman/termdict/internal/dict"
)

//go:embed core/wb1913_*.json.gz
var coreFiles embed.FS

//go:embed core/core_manifest.json
var manifestRaw []byte

// Store serves the embedded core subset.
type Store struct{}

// New returns the embedded store.
func New() Store { return Store{} }

// Name implements dict.Store.
func (s Store) Name() string { return "embedded-core" }

// Manifest returns the provenance/integrity document generated with
// the core files.
func (s Store) Manifest() (*Manifest, error) {
	var manifest Manifest
	if err := json.Unmarshal(manifestRaw, &manifest); err != nil {
		return nil, fmt.Errorf("embedded manifest invalid: %w", err)
	}
	return &manifest, nil
}

// Load implements dict.Store by decompressing every letter file.
func (s Store) Load() (map[string]dict.Entity, error) {
	entities := make(map[string]dict.Entity)

	matches, err := fs.Glob(coreFiles, "core/wb1913_*.json.gz")
	if err != nil {
		return nil, err
	}
	for _, name := range matches {
		batch, err := loadLetterFile(coreFiles, name)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		for word, entity := range batch {
			entities[word] = entity
		}
	}

	manifest, err := s.Manifest()
	if err != nil {
		return nil, err
	}
	if len(entities) != manifest.TotalEntries {
		return nil, fmt.Errorf(
			"embedded core holds %d entries but its manifest claims %d; rebuild with cmd/dbasebuild",
			len(entities), manifest.TotalEntries)
	}
	return entities, nil
}

func loadLetterFile(files embed.FS, name string) (map[string]dict.Entity, error) {
	openedFile, err := files.Open(name)
	if err != nil {
		return nil, err
	}
	defer openedFile.Close() //nolint:errcheck // read-only file

	gz, err := gzip.NewReader(openedFile)
	if err != nil {
		return nil, fmt.Errorf("gzip: %w", err)
	}
	defer gz.Close() //nolint:errcheck // read-only stream

	raw, err := io.ReadAll(io.LimitReader(gz, maxDecompressedSize+1))
	if err != nil {
		return nil, err
	}
	if int64(len(raw)) > maxDecompressedSize {
		return nil, fmt.Errorf("decompressed size exceeds limit")
	}

	var batch map[string]dict.Entity
	if err := json.NewDecoder(bytes.NewReader(raw)).Decode(&batch); err != nil {
		return nil, fmt.Errorf("decode: %w", err)
	}
	return batch, nil
}

const maxDecompressedSize = 64 << 20 // 64 MiB safety bound per letter file
